# -*- coding: utf-8 -*-
"""RadarBarcos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S7XAGY6dFyjFpCmLQlD6xxUieMN7YYsa
"""

import matplotlib.pyplot as plt
import numpy as np

GRID_SIZE = 40

def ler_barcos(nome_ficheiro):
    barcos = {}
    with open(nome_ficheiro, 'r') as f:
        for linha in f:
            partes = linha.strip().split()
            if len(partes) != 6:
                continue
            id_, x, y, ang, vel, tipo = partes
            x, y = int(x), int(y)
            barcos[id_] = {'x': x, 'y': y}
    return barcos

def desenhar_movimentos(barcos_t0, barcos_t1):
    fig, ax = plt.subplots(figsize=(10, 10))
    ax.set_xlim(0, GRID_SIZE)
    ax.set_ylim(0, GRID_SIZE)

    # Marcas de escala de 10 em 10
    ax.set_xticks(np.arange(0, GRID_SIZE + 1, 2))
    ax.set_yticks(np.arange(0, GRID_SIZE + 1, 2))
    ax.grid(True, which='both', color='lightgray', linewidth=0.5)
    ax.set_xticklabels(np.arange(0, GRID_SIZE + 1, 2))
    ax.set_yticklabels(np.arange(0, GRID_SIZE + 1, 2))
    ax.invert_yaxis()

    # Desenhar os barcos e setas de movimento
    for id_, pos_t0 in barcos_t0.items():
        x0, y0 = pos_t0['x'], pos_t0['y']
        texto = f"{id_} ({x0},{y0})"
        ax.text(x0, y0, texto, ha='center', va='center', fontsize=7, color='blue',
                bbox=dict(facecolor='white', edgecolor='none', pad=1))

        # Se existir no t1, desenhar seta
        if id_ in barcos_t1:
            x1, y1 = barcos_t1[id_]['x'], barcos_t1[id_]['y']
            dx = x1 - x0
            dy = y1 - y0
            ax.arrow(x0, y0, dx, dy, head_width=0.2, head_length=0.4, fc='red', ec='red')

    plt.title("Movimento dos Barcos (t0 → t1)")
    plt.xlabel("Longitude (X)")
    plt.ylabel("Latitude (Y)")
    plt.show()

# Leitura dos ficheiros
barcos_t0 = ler_barcos('antes.txt')
barcos_t1 = ler_barcos('depois.txt')

# Desenhar movimento
desenhar_movimentos(barcos_t0, barcos_t1)
